name: "STAGE: Deploy Jobs to Databricks"

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Stage
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Write to .databrickscfg
        run: |
          echo "[DEFAULT]" > $HOME/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> $HOME/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> $HOME/.databrickscfg

      - name: Run databricks bundle deploy
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: stage
        run: |
          databricks bundle validate
          databricks bundle deploy
        # run: databricks bundle deploy --debug
